# this is a config file for Poxy - a Doxygen + m.css front-end written in Python.
# https://github.com/marzer/poxy

name                = 'OpenIW4'
author              = 'William Roy'
description         = 'IW4 (game engine)'
cpp                 = 23
github              = 'OpenIW/OpenIW4'
license             = [ 'GPLv3', 'https://github.com/OpenIW/OpenIW4/blob/master/LICENSE' ]
favicon             = 'favicon.png'
navbar              = [ 'namespaces', 'annotated' ]
theme               = 'dark'

[warnings]
enabled             = true
undocumented        = true
treat_as_errors     = false

[sources]
recursive_paths     = [ '../src' ]
patterns            = [ '*.h' , '*.cpp' ]
